name: TIBCO JasperMobile for Android SDK
description: JasperMobile for Android SDK reference blog
meta_description: "TIBCO JasperMobile for Android SDK notes"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""

# Details for the RSS feed generator
url:            'http://jaspersoft.github.io/js-android-sdk'
author:         'Tom Koptel'

safe: true
lsi: false
